### ISSUE TITLE
New profiles from API does not work.

### ISSUE THREAD

**Issue by mangrisano** [mathiasertl/django-ca#168]
Hi,
I've just discovered that, if I want to set a new profile for new certificates via API, it doesn't work, even if I specify it in the **profile** key when calling the **/sign** endpoint.
Starting from your example, the bug persists, but there is no problem at all when using the command line.

Example profile:

```
CA_PROFILES:
  example:
    description: An example profile
    extensions:
      key_usage:
        value:
          - digitalSignature
      extended_key_usage:
        value:
          - clientAuth
```

Example request:

```
{
  "algorithm": "SHA-256",
  "autogenerated": false,
  "csr": "-----BEGIN CERTIFICATE REQUEST-----...-----END CERTIFICATE REQUEST-----",
  "profile": "example",
  "subject": [
    {
      "oid": "2.5.4.13",
      "type": "description",
      "value": "1.0"
    }
}
```
Version **django-ca: 2.2.1**
