### ISSUE TITLE
CA_PROFILES expiration time is ignored

### ISSUE THREAD

**Issue by DonOtuseGH** [mathiasertl/django-ca#87]
Hello,

using the django-ca (latest docker image) i realised, that profiles `expires` parameter seems to be ignored. I used the following additional profile, which is mapped into the container via `docker-compose.override.yml`:

`
volumes: - ./localsettings.yaml:/usr/src/django-ca/ca/conf/compose/99-localsettings.yaml
`

**localsettings.yaml:**

```
CA_DEFAULT_EXPIRES: 365
CA_PROFILES:
  server_3y:
    description: A certificate for a webserver with 3 years validity time.
    expires: 1095
    extensions:
      extended_key_usage:
        critical: false
        value:
        - serverAuth
      key_usage:
        critical: true
        value:
        - digitalSignature
        - keyEncipherment
    subject: /O=MyOrg/OU=Lab
```

As a result, the certificate contains the correct `subject` and `extensions`, but has default validity time of 1 year. Giving parameter `--expires 1095` in addition works for sure.

Could you please verify and solve this as well?

Thank you!
