### ISSUE TITLE
CA_DEFAULT_SUBJECT

### ISSUE THREAD

**Issue by doubledipped** [mathiasertl/django-ca#95]
I wonder if someone could post an example of how to set CA_DEFAULT_SUBJECT in a localsettings.yaml file please?

I am using the latest release via docker-compose and I would really like to be able to set defaults to be used with all certificate profiles but I just can't seem to get the syntax correct. The release notes state that this has been migrated from a dict object to a tuple, but I would really appreciate an example of how to define the subject in an an external yaml file.

Many thanks

**Comment by mathiasertl** [comment]
Hi @doubledipped !

```quote
but I would really appreciate an example of how to define the subject in an an external yaml file.
```

I could not agree more that this should be part of the documentation, and it's shamefully not. To get you started, here is an example from my config... with a specific override in a dedicated profile:

```yaml
CA_DEFAULT_SUBJECT:
        - ["O", "DefaultOrg"]
        - ["OU", "Default OrgUnit"]
        - ["OU", "Default OrgUnit 2"]

CA_PROFILES:
  other_profile:
    # other config
    subject:
        - ["O", "MyOrg"]
        - ["OU", "My OrgUnit"]
        - ["OU", "My OrgUnit 2"]
```

I'll work on properly documenting this properly next, including all more exotic fields.

In the meantime, help your self to this dict for a complete list: https://github.com/mathiasertl/django-ca/blob/1.22.0/ca/django_ca/utils.py#L91 (note: location of this variable will change in a future release).
